### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by shendanpuff** [mavethee/yuzu-macos-builds-script#2]
1 error generated.
[1489/2268] Building CXX object src/core/CMakeFiles/core.dir/arm/arm_interface.cpp.o
ninja: build stopped: subcommand failed.
Build failed. Please check the build output for errors.

**Comment by shinra-electric** [comment]
This info is not really helpful. Provide information about your setup (Mac model, OS version, RAM etc), and export your terminal log as a text file and post here, we can have a look at it. 

<img width="307" alt="Screenshot 2023-08-03 at 13 08 50" src="https://github.com/mavethee/yuzu-macos-builds-script/assets/50119606/7bcc2a8c-4911-4191-bb69-030833f355f2">

**Comment by mavethee** [comment]
Closed due inactivity
