### ISSUE TITLE
Issues preventing build

### ISSUE THREAD

**Issue by shinra-electric** [mavethee/yuzu-macos-builds-script#6]
There are a few issues that are currently preventing Yuzu from building: 

- [x] LLVM@17 is required. Fixed in #5 
- [x] Vulkan headers v1.3.274 is required, but it was only released a couple of days ago. ~~Homebrew should update soon.~~ Updated in Homebrew. 
- [x] I encountered an issue with nx_tzb when building on Xcode 15. Not sure if this is still an issue, since the Vulcan issue is preventing me from progressing. Edit: Issue reported

**Comment by mavethee** [comment]
Yeah, I was planning to look into it once MVK gets updated! ^^
Thanks for PR.

**Comment by mavethee** [comment]
And yah, issue with `nx_tzb` is still there.
![CleanShot 2024-01-04 at 10 05 02@2x](https://github.com/mavethee/yuzu-macos-builds-script/assets/47083527/29dc50b0-9fbd-4882-94f9-cb7e93517fc8)

**Comment by shinra-electric** [comment]
The issue has been identified and the fix should be committed to master soon...

They added a macOS CI a while ago to prevent Mac regressions, but the CI is x86 and this issue only affected arm64...

Edit: Actually the fix needs to be applied to the external nx_tzdb dependency, so not sure how long that will take...

**Comment by shinra-electric** [comment]
All issues are fixed, the script works as expected.
